const component = {

    login: { url: '/' },
    joblist: { url: '/:url' },
    latestfresherjob: { url: '/fresher-jobs' },
    hiringfresherjob: { url: '/fresher-jobs' },
    // hiringfresherjob: { url: '/jobs/hiring-fresher' },
    RemoteJobs: { url: '/remote-jobs'},
    WorkFromHomeJobs: { url: '/work-from-home-jobs' },
    WalkInJobs: { url: '/walk-in-jobs' },
    PartTimeJobs: { url: '/part-time-jobs' },
    MostPopularVideoJdJob: { url: '/most-popluar-video-jd-jobs' },
    HotSectorVideoJdJob: { url: '/hot-sector-video-jd-jobs' },
    MostLikedVideoJdJob: { url: '/most-liked-video-jd-jobs' },
    jobdetails: { url: '/job/:url' },
    dashboard: { url: '/dashboard' },
    verifyEmail: { url: '/EmailVerification' },
    UpgradeSkills: { url: '/upgrade-skills' },
    signin: { url: '/signin' },
    register: { url: '/register' },
    jobsearchIndiaDetail: { url: '/search-jobs-in-india/:KEYWORD_URL' },
    companieslist: { url: '/list/companies' },
    topcompanieslist: { url: '/top-companies' },
    companydetails: { url: '/company/:url' },
    jobbycity: { url: '/job-by-city' },
    CityOverview: { url: '/overview/:city' },
    blog: { url: '/blog' },
    blogDetails: { url: '/blog-details' },
    faqs: { url: '/faq' },
    MobileSearch: { url: '/search' },
    faqDetails: { url: '/faq/[url]' },
    faqCategory: { url: '/faq-category/[url]' },
    jobsByLocation: { url: '/jobs-by-location' },
    jobsByCompany: { url: '/jobs-by-company' },
    jobsByCategory: { url: '/jobs-by-category' },
    jobsByDesignation: { url: '/jobs-by-designation' },

    jobsBySkill: { url: '/jobs-by-skill' },

    CompanyBrandings: { url: '/company-brandings' },
    HrTechnologySolutions: { url: '/hr-technology-solutions' },
    SponsoredJDs: { url: '/sponsored-jds' },
    aboutUs: { url: '/about-us' },
    privacyPolicy: { url: '/privacy-policy' },
    termsConditions: { url: '/terms-conditions' },
    forgotPassword: { url: '/forgot-password' },
    logout: { url: '/logout' },
    myRozgar: { url: '/my-rozgar' },
    editProfile: { url: '/edit-profile' },
    savedJobs: { url: '/saved-jobs' },
    ProfilePerformance: { url: '/profile-performance' },
    InboxMessage: { url: '/recruiter-message' },
    recommendedJobs: { url: '/recommended-jobs' },
    applicationStatus: { url: '/application-status' },
    applicationStatusById: { url: '/application-status/:id' },
    profilePreview: { url: '/profile/:URL' },
    profilePreviews: { url: '/profile' },
    blogDetail: { url: '/blog/:url' },
    homepage: { url: '/' },
    searchjob: { url: '/search-job' },
    GovernmentSearchJob:{url:'/search-government-job/:keyword'},
    PersonalRecruiter: { url: "/personal-recruiter" },
    // editblog: { url: '/blog-detail/:url' },

    blogCategory: { url: '/blog/category/:url' },
    resetPassword: { url: '/reset-password-page' },
    searchbBoglist: { url: '/blog-list/search=:keyword' },
    allRecommendedJobsList: { url: '/all-recommended-jobs' },
    Enquiry: { url: '/under-maintainance-:Enquiry' },
    jobsInNoida: { url: '/Enquiry' },
    reportIssue: { url: '/report-a-problem' },
    CreateJobAlert: { url: '/create-job-alert' },
    error: { url: '/error' },
    BySkills: { url: '/BySkills' },
    ByCompany: { url: '/ByCompany' },
    ShareAnInterview: { url: '/share-an-interview' },
    AddAnswer: { url: '/AddAnswer' },
    // Tracker:{url:'/affiliate/:url'},
    AllJobs: { url: '/browse-jobs' },
    JavaFullStack: { url: '/JavaFullStack' },
    governmentJobs: { url: '/government-jobs' },
    internationalJobs: { url: '/international-jobs' },
    profileUpload: { url: '/profile-upload' },
    //Profile Picture upload
    premiumJobs: { url: '/premium-jobs' },
    changePassword: { url: '/change-password' },
    featuredJobs: { url: '/featured-jobs' },
    // courseDetail: { url: '/course-detail/:url' },
    courseDetailById: { url: '/course-detail/:url/:COURSE_ID' },
    fulltimehiring: { url: '/full-time-hiring' },
    contracttualstaffing: { url: '/contractual-staffing' },
    hrmanagementsystem: { url: '/hrms' },
    marketingtechnology: { url: '/marketing-technology' },
    payrollautomation: { url: '/payroll-automation' },
    startupincubation: { url: '/startup-incubation' },
    thankYou: { url: '/Thank-You' },
    studyAbroad: { url: '/study-abroad' },
    admissionAssistance: { url: '/addmission-assistance' },
    interviewQuestion: { url: '/interview-questions' },
    blogauthor: { url: '/author/:author-profile' },
    JobSearchIndia: { url: '/job-search-india' },
    interviewQuestionBySkills: { url: '/interview-questions/skills' },
    interviewQuestionByCompany: { url: '/interview-questions/company' },
    interviewQuestionByDesignation: { url: '/interview-questions/designations' },
    interviewQuestionBySkillsId: { url: '/interview-questions/skills/:id' },
    interviewQuestionByCompanyId: { url: '/interview-questions/company/:id' },

    interviewQuestionByDesignationId: { url: '/interview-questions/designations/:id' },
    interviewAnswer: { url: '/interview-answer/:url' },
    studyAbroadScholarship: { url: '/study-abroad-scholarship' },
    testPreparation: { url: '/test-preparation' },
    travelGuidance: { url: '/travel-guidance' },
    visaApplicationAssistance: { url: '/visa-application-assistance' },
    coursesAdviceGuidance: { url: '/course-advice-guidance' },
    studyAbroadCounselling: { url: '/study-abroad-counselling' },
    visaCoverLetter: { url: '/visa-cover-letter' },
    sopWritingServices: { url: '/sop-writing-services' },
    lorWritingServices: { url: '/lor-writing-services' },
    resumeWritingServices: { url: '/resume-writing-services' },
    studyInAustralia: { url: '/study-in-australia' },
    studyInCanada: { url: '/study-in-canada' },
    studyInUk: { url: '/study-in-uk' },
    studyInUsa: { url: '/study-in-usa' },
    studyInItaly: { url: '/study-in-italy' },
    studyInIreland: { url: '/study-in-ireland' },
    studyInNewZealand: { url: '/study-In-new-zealand' },
    studyInSingapore: { url: '/study-in-singapore' },
    workabroad: { url: '/work-abroad' },
    careerAstrology: { url: '/career-astrology' },
    StudentsExplorer: { url: '/career-explorer' },
    CareerExplorerDetail: { url: '/college-details/:url' },
    ResumeForm: { url: 'resume-form' },
    resumeMaking: { url: 'resume-making' },
    ResumeViewOne: { url: '/resume-view' },
    ResumeViewTwo: { url: '/resume-view01' },
    ResumeViewThree: { url: '/resume-view02' },
    ResumeTemplateView01: { url: '/resume-template-view' },
    ResumeTemplateView02: { url: '/resume-template-view01' },
    ResumeTemplateView03: { url: '/resume-template-view03' },
    careerReport1Year: { url: '/career-report-1-year' },
    remedialSolutionForCareer: { url: '/remedial-solution-for-career' },
    strengthReadingForCareer: { url: '/strength-reading-for-career' },
    careerAsk1Question: { url: '/career-ask-1-question' },
    careerAsk3Question: { url: '/career-ask-3-question' },
    careerReport2Year: { url: '/career-report-2-year' },
    careerReport3Year: { url: '/career-report-3-year' },
    careerReport5Years: { url: '/career-report-5-year' },
    educationLoan: { url: '/loans-advances' },
    workinAustralia: { url: '/work-in-australia' },
    workinCanada: { url: '/work-in-canada' },
    companyInterviewAnswer: { url: '/interview-answers/:url' },
    designationInterviewAnswer: { url: '/interview-answers-designation/:url' },
    //interviewQuestion by Company

    //interviewQuestion by Company
    discussionForum: { url: '/discussion-forum' },
    discussionForumCategory: { url: '/discussion-forum/category/:category' },
    buyCourse: { url: '/buy-course/:url' },
    ResumeMaking: { url: '/resume-making' },
    TemplatePreview: { url: '/template-preview' },
    TemplatePreview01: { url: '/template-preview01' },
    TemplatePreview02: { url: '/template-preview02' },
    TemplatePreview04: { url: '/template-preview04' },
    TemplatePreview05: { url: '/template-preview05' },
    TemplatePreview06: { url: '/template-preview06' },
    TemplatePreview07: { url: '/template-preview07' },
    TemplateEdit: { url: '/template-edit' },
    TemplateEdit01: { url: '/template-edit01' },
    TemplateEdit02: { url: '/template-edit02' },
    TemplateEdit04: { url: '/template-Edit04' },
    TemplateEdit05: { url: '/template-Edit05' },
    TemplateEdit06: { url: '/template-Edit06' },
    TemplateEdit07: { url: '/template-Edit07' },
    AnswerByQuestion: { url: '/interview-question-answer/:id' },
    discussionForumDetails: { url: '/topic/:url' },
    discussionForumSignIn: { url: '/discussionForumSignIn' },
    resumePreview: { url: '/preview-resume' },
    workinUK: { url: '/work-in-uk' },
    resumeTemplate1: { url: '/resume-template-1' },
    workinUSA: { url: '/work-in-usa' },
    workinIreland: { url: '/work-in-ireland' },
    workinNewZealand: { url: '/work-in-new-zealand' },
    workinSingapore: { url: '/work-in-singapore' },
    workinMalaysia: { url: '/work-in-malaysia' },
    resumeTemplate2: { url: '/resume-template-2' },
    resumeTemplate3: { url: '/resume-template-3' },
    resumeTemplate4: { url: '/resume-template-4' },
    ResumeChooseTemplate: { url: '/create-cv-choose-template' },
    FullStackJobs: { url: '/full-stack-jobs/:KEYWORD_URL' },
    FullStackDeveloperJobsInIndia: { url: '/full-stack-developer-jobs-in-india' },

    // resumeTemplate3: {url: '/resume-template-3'},
    // resumeTemplate4: {url: '/resume-template-4'},
    // FullStackJobs: {url: '/full-stack-jobs/:KEYWORD_URL'},
    // FullStackDeveloperJobsInIndia: {url: '/full-stack-developer-jobs-in-india'},


    commonSearchQue: { url: '/interview-search-questions/' },
    commonSearchQuestion: { url: '/interview-search-questions/:Keyword' },
    commonSearchAnswer: { url: '/interview-questions/:url' },
    ads: { url: '/ads' },
    messageById: { url: '/recruiters-message' },
    PMRozgarMela: { url: '/pm-rozgar-mela' },
    Swiggy: { url: '/company/swiggy-16264' },
    SwiggyJobs: { url: '/swiggy-jobs' },
    SwiggyAboutUs: { url: '/swiggy-about-us' },
    SwiggyLife: { url: '/swiggy-life' },
    Greenlamindustries: { url: '/company/greenlam-industries-limited-24354' },
    GreenlamindustriesJobs: { url: '/greenlam-industries-jobs' },
    GreenlamindustriesAboutUs: { url: '/greenlam-industries-about-us' },
    GreenlamindustriesLife: { url: '/greenlam-industries-life' },
    GovernmentResult: { url: '/government-result/:url' },
    Sitemap: {url: '/sitemap'},
    GovernmentResultState: { url: '/government-jobs-result' },
    updateTemplate01: { url: '/template-update01' },
    GovernmentStatesJobs:{url:'/government-jobs/:url'},
    GovernmentState:{url:'/government-jobs'},
    GovernmentJobsDetails:{url:'/government-jobs-details/:url'},
    GovtDeptResult:{url:'/government-results/:state/:department/:url/:id'},
    GovtDeptJobs:{url:'/government-job/:state/:department/:url/:id'},
    updateTemplate02: { url: '/template-update02' },
    updateTemplate03: { url: '/template-update03' },
    updateTemplate04: { url: '/template-update04' },
    updateTemplate05: { url: '/template-update05' },
    updateTemplate06: { url: '/template-update06' },
    unsubscribe: { url: '/unsubscribe/:CANDIDATE_ID' },
    updateTemplate07: { url: '/template-update07' },
    coupon: { url: '/rewards' }
}

const title = {
    Homepage: "Jobs - Recruitment - Job Search -  Employment - Job Vacancies - Rozgar.com",
    MobileSearch: "Jobs - Recruitment - Job Search -  Employment - Job Vacancies - Rozgar.com",
    Joblist: "JobsList",
    FresherJoblist: "Freshers Jobs List - Rozgar.com",
    InternationalJoblist: "International Jobs List - Rozgar.com",
    Signin: "Signin",
    CityOverview: "City Overview - Rozgar.com",
    Register: "Register",
    CreateJobAlert: "Create Job Alert - Rozgar.com",
    ForgotPassword: "Forgot Password",
    ResetPassword: "Reset Password",
    Companieslist: "All Companies - Rozgar.com",
    Companydetails: "Company Details",
    Jobbycity: "Job By City",
    JobsInNoida: "jobs in Noida",
    Blog: "Blog | Rozgar.com",
    BlogDetail: "Blog Details",
    Faqs: "FAQ | Rozgar.com",
    JobsByLocation: "Browse Jobs by Location - Search Jobs in State/City - Rozgar.com",
    JobsByCompany: "Browse Jobs by Company - Jobs in Top Companies - Rozgar.com",
    JobsByCategory: "Browse Jobs by Functional Area/Industry - Rozgar.com",
    JobsByDesignation: "Browse Jobs by Designation - Rozgar.com",
    JobsBySkill: "Browse Jobs by IT/Non-IT Skills - Rozgar.com",
    AboutUs: "About Us",
    PrivacyPolicy: "Privacy Policy",
    TermsConditions: "Terms Conditions",
    MyRozgar: "My Rozgar",
    EditProfile: "Edit Profile",
    SavedJobs: "Saved Jobs | Rozgar.com",
    ProfilePerformance: "Profile Performance | Rozgar.com",
    InboxMessage: "Inbox Message | Rozgar.com",
    RecommendedJobs: "Recommended Jobs",
    ApplicationStatus: "Application Status",
    CreateRozgarProfile: "FQA Details",
    ProfilePreview: "Profile Preview",
    faqCategory: "FAQ | Rozgar.com",
    changePassword: "ChangePassword | Rozgar.com",
    faqDetail: "FAQ | Rozgar.com",
    AddAnswer: "Add Answer | Rozgar.com",
    recommendedJobsList: "All Recommended Jobs | Rozgar.com",
    Enquiry: 'We are Working on this | Rozgar.com',
    BySkill: 'By Skills | Rozgar.com',
    ShareAnInterview: 'Share An Interview | Rozgar.com',
    AllJobs: ' Browse Jobs by Company, Location, Skills, Designation & Industry | Rozgar.com',
    topcompanies: `Top Companies - Rozgar.com`,
    fulltimehiring: 'fulltime jobs - Rozgar.com',
    contracttualstaffing: 'contracttual-staffing - Rozgar.com',
    hrmanagementsystem: 'Human Resource Management System - Rozgar.com',
    marketingtechnology: 'marketing-technology - Rozgar.com',
    PersonalRecruiter: 'Get your own Personal Recruiter @ 4999 Only | Rozgar',
    payrollautomation: 'payroll-automation - Rozgar.com',
    startupincubation: 'startup-incubation - Rozgar.com',
    DiscussionForum: 'Discussion Forum | Rozgar.com',
    thankYou: 'Thank-You - Rozgar.com',
    StudyAbroad: 'Study Abroad - Rozgar.com',
    AdmissionAssistance: 'Admission Assistance - Rozgar.com',
    studyAbroadScholarship: 'Study Abroad Scholarship -Rozgar.com',
    DiscussionForumCategory: 'career | Category | Discussion Forum | Rozgar.com',
    homeAllQuestions: 'Interview Question | Rozgar.com',
    homeBySkill: 'By-Skill | Interview Questions | Rozgar.com',
    homeByCompany: 'By-Company | Interview Questions | Rozgar.com',
    homeByRole: 'By-Role | Interview-questions | Rozgar.com',
    interviewQuestion: ' skills | Interview Questions | Rozgar.com',
    TestPreparation: 'Test-Preparation - Rozgar.com',
    travelGuidance: 'Travel-Guidance - Rozgar.com',
    visaApplicationAssistance: 'Visa Application Assistance - Rozgar.com',
    coursesAdviceGuidance: 'Courses Advice Guidance - Rozgar.com',
    studyAbroadCounselling: 'Study Abroad Counselling - Rozgar.com',
    visaCoverLetter: 'Visa Cover Letter - Rozgar.com',
    sopWritingServices: 'SOP Writing Services - Rozgar.com',
    lorWritingServices: 'LOR Writing Services - Rozgar.com',
    resumeWritingServices: 'Resume Writing Services - Rozgar.com',
    studyInAustralia: 'Study in Australia - Rozgar.com',
    studyInCanada: 'Study in Canada - Rozgar.com',
    studyInUk: 'Study in UK - Rozgar.com',
    studyInUsa: 'Study in USA - Rozgar.com',
    studyInItaly: 'Study in Italy - Rozgar.com',
    studyInIreland: 'Study in Ireland - Rozgar.com',
    studyInNewZealand: 'Study In New Zealand - Rozgar.com',
    studyInSingapore: 'Study In Singapore - Rozgar.com',
    interviewQuestionCompany: 'Company | Interview Questions | Rozgar.com',
    ReportIssue: 'Report-a-problem - Rozgar.com',
    internationalWorkVisas: 'International Work Visas -Rozgar.com',
    interviewAnswer: 'Question | Interview Question | Rozgar.com',
    commonInterviewAnswer: 'Questions | Interview Question | Rozgar.com',
    careerAstrology: 'Career Astrology - Rozgar.com',
    StudentsExplorer: 'Career Explorer - Rozgar.com',
    CareerExplorerDetail: 'Career Explorer Detail- Rozgar.com',
    ResumeViewOne: 'Resume View - Rozgar.com',
    ResumeViewTwo: 'Resume View - Rozgar.com',
    ResumeViewThree: 'Resume View - Rozgar.com',
    ResumeTemplateView01: 'Resume Template View - Rozgar.com',
    ResumeTemplateView02: 'Resume Template View - Rozgar.com',
    careerReport1Year: 'Career Report 1 Year - Rozgar.com',
    remedialSolutionForCareer: 'Remedial Solution For Career - Rozgar.com',
    strengthReadingForCareer: 'Strength Reading For Career - Rozgar.com',
    careerAsk1Question: 'Career Ask 1 Question - Rozgar.com',
    careerAsk3Question: 'Career Ask 3 Question - Rozgar.com',
    careerReport2Year: 'Career Report 2 Year - Rozgar.com',
    careerReport3Year: 'Career Report 3 Year - Rozgar.com',
    careerReport5Years: 'Career Report 5 Year - Rozgar.com',
    workinAustralia: 'Work in Australia - Rozgar.com',
    workinCanada: 'Work in Canada - Rozgar.com',
    educationLoan: 'Education Loan - Rozgar.com',
    workinUK: 'Work in UK - Rozgar.com',
    workinUSA: 'Work in USA - Rozgar.com',
    workinIreland: 'Work in Ireland - Rozgar.com',
    workinNewZealand: 'Work in New Zealand - Rozgar.com',
    workinSingapore: 'Work in Singapore - Rozgar.com',
    workinMalaysia: 'Work in Malaysia - Rozgar.com',
    JobSearchIndia: 'Job Search India | Rozgar.com',

    ResumeMaking: 'Resume Making - Rozgar.com',
    TemplatePreview: 'Template Preview - Rozgar.com',
    TemplatePreview01: 'Template Preview01 - Rozgar.com',
    TemplatePreview02: 'Template Preview02 - Rozgar.com',
    TemplatePreview04: 'Template Preview04 -Rozgar.com',
    TemplatePreview05: 'Template Preview05 - Rozgar.com',
    TemplatePreview06: 'Template Preview06 - Rozgar.com',
    TemplatePreview07: 'Template Preview07 - Rozgar.com',
    TemplateEdit: 'Create Free CV - Template-01 - Rozgar.com',
    TemplateEdit01: 'Create Free CV - Template-02 - Rozgar.com',
    TemplateEdit02: 'Create Free CV - Template-03 - Rozgar.com',
    TemplateEdit04: 'Create Free CV - Template-04 - Rozgar.com',
    TemplateEdit05: 'Create Free CV - Template-05 - Rozgar.com',
    TemplateEdit06: 'Create Free CV - Template-06 - Rozgar.com',
    TemplateEdit07: 'Create Free CV - Template-07 - Rozgar.com',
    discussionForumDetails: 'Discussion Forum Details -Rozgar.com',
    ResumePreview: 'Resume Preview - Rozgar.com',
    ResumePreview01: 'Resume Preview 01 - Rozgar.com',
    ResumePreview02: 'Resume Preview 02 - Rozgar.com',
    Threadtitle: 'Threadtitle | Discussion Forum | Rozgar.com',
    page404: 'Not Found',
    interviewQuestionByDesignation: ':Designation | Designation | Interview Question | Rozgar',
    resumeTemplate1: 'Resume Template one - Rozgar.com',
    resumeTemplate2: 'Resume Template Two - Rozgar.com',
    resumeTemplate3: 'Resume Template Three - Rozgar.com',
    resumeTemplate4: 'Resume Template Four - Rozgar.com',

    Swiggy: 'Swiggy - Rozgar.com',
    SwiggyJobs: 'Swiggy Jobs - Rozgar.com',
    SwiggyAboutUs: 'Swiggy About Us - Rozgar.com',
    SwiggyLife: 'Swiggy Life - Rozgar.com',
    SeoKeywordsJob: 'Seo Keywords Job - Rozgar.com',
    jobsinIndia: 'Full Stack Developer Jobs in India | Rozgar.com',
    PMRozgarMela: 'PM Rozgar Mela | Rozgar.com',
    TemplateUpdate01: 'Create Free CV - Template-01 -Rozgar.com',
    TemplateUpdate02: 'Create Free CV - Template-02 -Rozgar.com',
    TemplateUpdate03: 'Create Free CV - Template-03 -Rozgar.com',
    TemplateUpdate04: 'Create Free CV - Template-04 -Rozgar.com',
    TemplateUpdate05: 'Create Free CV - Template-05 -Rozgar.com',
    TemplateUpdate06: 'Create Free CV - Template-06 -Rozgar.com',
    TemplateUpdate07: 'Create Free CV - Template-07 -Rozgar.com',
}

const keys = {
    token: 'tk.rozgar.com',
    userDetails: 'ud.rozgar.com',
    ctoken: 'ctk.rozgar.com',
    cd: 'cd.rozgar.com',
    cLoggedIn: 'logged_in.rozgar.com',
    c_remeber_me: 'remeber.rozgar.com',
    loginData: 'loginData',
    JobUrl: 'JobUrl',
    addAndUpdate: 'addAndUpdate',
    Url: 'Url',
    register: 'register',
    saveJobId: 'saveJobId',
    Keyword:'Keyword'
}

const version = {
    web: 1.0
}

const currency = {
    indianRupee: '₹'
}
const build = {

    version: 'Rozgar-Version 3.1.1'


}
export const dev_canocical = {
    d_canonical: 'https://qa.rozgar.com/'

}

const MasterData = {

    "SETTING_ID": 1,
    PHONE_NUMBER: "+91-9560482266",
    EMAIL_ID: "contact@rozgar.com",
    FACEBOOK_URL: "https://www.facebook.com/RozgarGlobal",
    TWITTER_URL: "https://twitter.com/rozgar_india?lang=en",
    YOUTUBE_URL: "https://www.youtube.com/channel/UCfTrm4NxEoY4U8cNIMyAuxw",
    LINKEDIN_URL: "https://www.linkedin.com/company/rozgar/?originalSubdomain=in",
    ACTUAL_PRICE: "14000",
    DISCOUNT_PRICE: "4999",
    WHATSAPP_NUMBER: "+919560482266",
    MODIFIED_BY: 1,
    CREATED_ON: "2022-10-11T13:21:12.000Z",
    CREATED_BY: 0,
    MODIFIED_ON: "2022-10-11T13:21:12.000Z",
    USA_ADDRESS: "1123 Broadway, Suite 301, New York, NY 10010",
    JOBS_AND_COUNTING: "1,156,843",
    CLIENTS: "9,593",
    CANDIDATE: "12,333,676",
    RECRUITER: "98,653",
    SINGAPORE_ADDRESS: "68 Circular Road #02-01 Singapore (049422)",
    INDIA_ADDRESS: "Head office: A-51, Sector 16, Noida, U.P. - 201301",
    DUBAI_ADDRESS: "Office No. 301, Malak Ibrahim Muhammad Hussain Rai Business Bay, Dubai - 346-466"
}

const course_list = [
    {
        COURSE_ID: 1,
        COURSE_TITLE: "Java Full Stack",
        URL: "java-full-stack"
    },
    {
        COURSE_ID: 2,
        COURSE_TITLE: "Python Full Stack",
        URL: "python-full-stack"
    },
    {
        COURSE_ID: 3,
        COURSE_TITLE: "Software Testing",
        URL: "software-testing"
    }
]


 
export const  s3_url  = 'https://s3rozgar.s3.ap-south-1.amazonaws.com/resume/'

const metaDescription = " - Search, find and apply to job opportunities at Rozgar.com - India's leading Job Portal. Bring your perception, imagination and healthy neglect for the impossible. For query call us at +91-8800277577 or email us at contact@rozgar.com"
export default { component, keys, version, currency, title, build, metaDescription, MasterData, course_list }

